swagger: '2.0'
info:
  title: Tree Permit API
  version: v1
host: tree-permit-api-handler-643296747345.europe-west1.run.app
basePath: /
schemes:
  - https
paths:
  /tree-permits:
    get:
      summary: Fetch Tree Permits
      operationId: fetchTreePermits
      produces:
        - application/json
      responses:
        '200':
          description: A JSON array of tree permits
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                settlement:
                  type: string
                licenseType:
                  type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      x-google-backend:
        address: https://tree-permit-api-handler-643296747345.europe-west1.run.app/tree-permits
